export const categories = [
  { name: 'Dexes', des: 'Protocols where you can swap/trade cryptocurrency' },
  { name: 'Lending', des: '' },
  { name: 'Liquid Staking', des: '' },
  { name: 'CDP', des: '' },
  { name: 'Bridge', des: '' },
  { name: 'Yield', des: '' },
  { name: 'Services', des: '' },
  { name: 'Derivatives', des: '' },
  { name: 'Algo-Stables', des: '' },
  { name: 'Yield Aggregator', des: '' },
  { name: 'Cross Chain', des: '' },
  { name: 'Synthetics', des: '' },
  { name: 'Launchpad', des: '' },
  { name: 'Insurance', des: '' },
  { name: 'Reserve Currency', des: '' },
  { name: 'Payments', des: '' },
  { name: 'Privacy', des: '' },
  { name: 'Indexes', des: '' },
  { name: 'Options', des: '' },
  { name: 'NFT Lending', des: '' },
  { name: 'RWA', des: '' },
  { name: 'Leveraged Farming', des: '' },
  { name: 'Staking', des: '' },
  { name: 'NFT Marketplace', des: '' },
  { name: 'Uncollateralized Lending', des: '' },
  { name: 'Exotic Options', des: '' },
  { name: 'Farm', des: '' },
  { name: 'Prediction Market', des: '' },
  { name: 'Gaming', des: '' },
  { name: 'RWA Lending', des: '' },
  { name: 'Oracle', des: '' },
];
